[package]
edition = "2021"
name = "rust-tools"
version = "0.1.0"

[lib]
name = "rust_tools"
path = "src/lib.rs"

[dependencies]
csv = "1.3.1"
itertools = "0.13.0"
lazy_static = "1.5.0"
byteorder = "1.3"
serde = {version = "1.0.215", features = ["derive"]}
image = "0.25.5"
